// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using horrorarpg_backend.Infrastructure;

#nullable disable

namespace horrorarpg_backend.Infrastructure.Migrations
{
    [DbContext(typeof(ArpgDbContext))]
    partial class ArpgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("horrorarpg_backend.Core.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("horrorarpg_backend.Core.Entities.UserSaveEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Health")
                        .HasColumnType("real");

                    b.Property<float>("Mana")
                        .HasColumnType("real");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserSaves");
                });

            modelBuilder.Entity("horrorarpg_backend.Core.Entities.UserSaveEntity", b =>
                {
                    b.HasOne("horrorarpg_backend.Core.Entities.UserEntity", "User")
                        .WithOne("UserSave")
                        .HasForeignKey("horrorarpg_backend.Core.Entities.UserSaveEntity", "UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("horrorarpg_backend.Core.Entities.UserEntity", b =>
                {
                    b.Navigation("UserSave");
                });
#pragma warning restore 612, 618
        }
    }
}
